version: '3.8'

services:
  uzabase-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uzabase-app
    volumes:
      - ./outputs:/app/outputs  # Mount the outputs directory to persist data
      - ./logs:/app/logs        # Mount the logs directory to persist logs
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["sh", "-c"]
    command: >
      "python src/run.py process_data --cfg config/cfg.yaml --dataset news --dirout outputs &&
       python src/run.py process_data_all --cfg config/cfg.yaml --dataset news --dirout outputs"
